name: Manual Maven CI

on:
  workflow_dispatch: # This event allows triggering the workflow manually

jobs:
  build:

    runs-on: ubuntu-latest  #container env called runner that runs our code

    steps: 

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'

    # - name: Cache Maven dependencies
    #   uses: actions/cache@v3
    #   with:
    #     path: "${{ github.workspace }}/repository"
    #     key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
    #     restore-keys: |
    #       ${{ runner.os }}-maven-
    #     fail-on-cache-miss: false

    # - name: Debug Cache
    #   run: |
    #     cat ~/.m2/settings.yaml
    #     echo "Cache directory contents:"
    #     cat ~/.m2/settings.yaml


    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Test with Maven
      run: mvn test --file pom.xml
